DEBUG 2021-11-05 10:07:27.940 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-11-05 10:07:27.940 UTC: 	 Running on: Linux earth.crc.nd.edu 3.10.0-1160.45.1.el7.x86_64 #1 SMP Fri Sep 24 10:17:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux
DEBUG 2021-11-05 10:07:27.940 UTC: 	 Executing command: 'kill'
DEBUG 2021-11-05 10:07:27.940 UTC: 	 Found CRAB cache file /afs/crc.nd.edu/user/r/rgoldouz/.crab3
ERROR 2021-11-05 10:07:27.942 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/crc.nd.edu/user/r/rgoldouz/Ntupleproducer/NanoAOD/CMSSW_10_2_18/src/PhysicsTools/NanoAODTools/crab/crab_Etop_nanoAODv9_DATA
ERROR 2021-11-05 10:07:27.942 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/crc.nd.edu/user/r/rgoldouz/Ntupleproducer/NanoAOD/CMSSW_10_2_18/src/PhysicsTools/NanoAODTools/crab/crab_Etop_nanoAODv9_DATA
INFO 2021-11-05 10:07:27.944 UTC: 	 Log file is /afs/crc.nd.edu/user/r/rgoldouz/Ntupleproducer/NanoAOD/CMSSW_10_2_18/src/PhysicsTools/NanoAODTools/crab/crab.log
DEBUG 2021-11-05 10:08:12.445 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-11-05 10:08:12.445 UTC: 	 Running on: Linux earth.crc.nd.edu 3.10.0-1160.45.1.el7.x86_64 #1 SMP Fri Sep 24 10:17:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux
DEBUG 2021-11-05 10:08:12.445 UTC: 	 Executing command: 'submit'
DEBUG 2021-11-05 10:08:12.446 UTC: 	 Found CRAB cache file /afs/crc.nd.edu/user/r/rgoldouz/.crab3
DEBUG 2021-11-05 10:08:12.448 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2021-11-05 11:27:57.149 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-11-05 11:27:57.149 UTC: 	 Running on: Linux earth.crc.nd.edu 3.10.0-1160.45.1.el7.x86_64 #1 SMP Fri Sep 24 10:17:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - Red Hat Enterprise Linux
DEBUG 2021-11-05 11:27:57.149 UTC: 	 Executing command: 'status'
DEBUG 2021-11-05 11:27:57.149 UTC: 	 Found CRAB cache file /afs/crc.nd.edu/user/r/rgoldouz/.crab3
ERROR 2021-11-05 11:27:57.151 UTC: 	 Error: crab_Etop_nanoAODv9_DATA/crab_UL17_TTZToLLNuNu_M_10/ is not a valid CRAB project directory.
ERROR 2021-11-05 11:27:57.151 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Etop_nanoAODv9_DATA/crab_UL17_TTZToLLNuNu_M_10/ is not a valid CRAB project directory.
INFO 2021-11-05 11:27:57.153 UTC: 	 Log file is /afs/crc.nd.edu/user/r/rgoldouz/Ntupleproducer/NanoAOD/CMSSW_10_2_18/src/PhysicsTools/NanoAODTools/crab/crab.log
